import { Ubuntu } from 'next/font/google'
const ubuntu = Ubuntu({ weight: ["300", "400", "500"], subsets: ["latin"] })

export const metadata = {
  title: 'talentscrew ',
  description: 'Generated by create next app',
}

export default function LoginRootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={ubuntu.className}>
        {children}
      </body>
    </html>
  )
}
